### ISSUE TITLE
TypeError: cb is not a function

### ISSUE THREAD

**Issue by arch-herobrine** [trumank/scratch-api#43]
TypeError: cb is not a function
    at /home/runner/bot/node_modules/scratch-api/scratchapi.js:103:7
    at IncomingMessage.<anonymous> (/home/runner/bot/node_modules/scratch-api/scratchapi.js:37:37)
    at IncomingMessage.emit (node:events:402:35)
    at IncomingMessage.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1343:12)
   pls fix

**Comment by arch-herobrine** [comment]
![image](https://user-images.githubusercontent.com/112319383/191876097-956052d4-710d-4763-934b-a7acddd7e20a.png)
